### ISSUE TITLE
Cannot use `ASDF_FFMPEG_ENABLE=all`: GnuTLS and OpenSSL must not be enabled at the same time

### ISSUE THREAD

**Issue by UlyssesZh** [acj/asdf-ffmpeg#3]
**Describe the bug**

Cannot use `ASDF_FFMPEG_ENABLE=all`: GnuTLS and OpenSSL must not be enabled at the same time

**Steps to reproduce**

```shell
ASDF_FFMPEG_ENABLE=all rtx install ffmpeg@6.1
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by acj** [comment]
Thanks for the report. Does your use case need every option to be enabled? Could you enable a smaller subset of them instead?

I think the simplest fix here is to remove the `all` meta-option. I added it for convenience when testing the plugin itself, but it's not usually what you want -- there are dozens of options, and most of them require you to compile or install more libraries before you can build ffmpeg.

**Comment by UlyssesZh** [comment]
Removing `all` is fine.
